# Generated by Django 2.2.8 on 2020-03-11 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='covers',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
